language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libfftw3-dev
      - libjsoncpp-dev
      - libboost-python-dev
      - libopencv-dev

sudo: required

install:
  - git clone https://github.com/jeremyfix/popot.git
  - cd popot
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  - sudo make install
  - cd ../..

script:
  - mkdir build
  - cd build
  - cmake ..
  - make