sudo: required
services:
    - docker

before_install:
    - docker pull

HAVE A LOOK TO : https://docs.travis-ci.com/user/docker/
we can use a dockerfile given in the github repo to build our own image...!

language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libfftw3-dev
      - libjsoncpp-dev
      - libboost-python-dev
      - libopencv-dev

sudo: required

install:
  - git clone https://github.com/jeremyfix/popot.git
  - cd popot
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  - sudo make install
  - cd ../..

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
