os: linux
language: minimal

services:
    - docker

before_install:
    - docker build -t neuralfield/latest .
    - docker run neuralfield/latest /bin/sh -c "neuralfield-example-000"

after_success:
    # see https://github.com/codecov/example-cpp11-cmake/blob/master/CMakeLists.txt
    # Creating report
    - docker run neuralfield/latest /bin/sh -c "cd ${TRAVIS_BUILD_DIR}; lcov --directory . --capture --output-file coverage.info; lcov --remove coverage.info '/usr/*' --output-file coverage.info; lcov --list coverage.info; bash <(curl -s https://codecov.io/bash) || echo \"Codecov did not collect coverage reports\""
